### ISSUE TITLE
Issue when resizing terminal window smaller after initial load

### ISSUE THREAD

**Issue by dombarnes** [ttscoff/mdless#10]
I seem to have an issue if I resize the terminal window smaller than it was on initial load. Using iTerm2 3.0.2. Possibly related to #3?

```
/Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/lib/mdless/converter.rb:417:in `*': negative argument (ArgumentError)
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/lib/mdless/converter.rb:417:in `block (2 levels) in convert_markdown'
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/lib/mdless/converter.rb:413:in `map'
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/lib/mdless/converter.rb:413:in `block in convert_markdown'
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/lib/mdless/converter.rb:393:in `gsub!'
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/lib/mdless/converter.rb:393:in `convert_markdown'
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/lib/mdless/converter.rb:117:in `block in initialize'
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/lib/mdless/converter.rb:105:in `each'
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/lib/mdless/converter.rb:105:in `initialize'
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/bin/mdless:17:in `new'
    from /Users/domster83/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mdless-0.0.9/bin/mdless:17:in `<top (required)>'
    from /Users/domster83/.rbenv/versions/2.3.1/bin/mdless:22:in `load'
    from /Users/domster83/.rbenv/versions/2.3.1/bin/mdless:22:in `<main>'
```

**Comment by ttscoff** [comment]
This should be fixed in recent releases. Closing out.
