### ISSUE TITLE
Remove dependency on git

### ISSUE THREAD

**Issue by TMiguelT** [ttscoff/mdless#27]
If `git` is not installed on a system but you try to run `mdless`, you get the following error:

```
$ mdless README.md 
Traceback (most recent call last):
	10: from /usr/local/bin/mdless:23:in `<main>'
	 9: from /usr/local/bin/mdless:23:in `load'
	 8: from /var/lib/gems/2.5.0/gems/mdless-0.0.10/bin/mdless:17:in `<top (required)>'
	 7: from /var/lib/gems/2.5.0/gems/mdless-0.0.10/bin/mdless:17:in `new'
	 6: from /var/lib/gems/2.5.0/gems/mdless-0.0.10/lib/mdless/converter.rb:121:in `initialize'
	 5: from /var/lib/gems/2.5.0/gems/mdless-0.0.10/lib/mdless/converter.rb:737:in `printout'
	 4: from /var/lib/gems/2.5.0/gems/mdless-0.0.10/lib/mdless/converter.rb:692:in `page'
	 3: from /var/lib/gems/2.5.0/gems/mdless-0.0.10/lib/mdless/converter.rb:692:in `fork'
	 2: from /var/lib/gems/2.5.0/gems/mdless-0.0.10/lib/mdless/converter.rb:700:in `block in page'
	 1: from /var/lib/gems/2.5.0/gems/mdless-0.0.10/lib/mdless/converter.rb:745:in `which_pager'
/var/lib/gems/2.5.0/gems/mdless-0.0.10/lib/mdless/converter.rb:745:in ``': No such file or directory - git (Errno::ENOENT)
```

I suspect this is because you're checking the git config for a pager, but ideally the program would skip this step if it can't find `git`, rather than crashing. The reason this matters is when you're in a minimal environment, e.g. a VPS or a docker container, where you need to quickly view a markdown file but you don't want to have to install git.

**Comment by ttscoff** [comment]
Care to submit a pull request? It's a valid concern but I don't have 
much time right now for patching it up.

-Brett
