### ISSUE TITLE
mdless 1.0.3 won't load any files: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mdless/hash (LoadError)

### ISSUE THREAD

**Issue by jjarava** [ttscoff/mdless#36]
I've just updated to the latest version of `mdless`, v1.0.3, and now I can't load any file, or even call it without any params.

I've updated with:

```bash
$ sudo gem update mdless
Updating installed gems
Updating mdless
Fetching: mdless-1.0.3.gem (100%)
Successfully installed mdless-1.0.3
invalid options: -ri
(invalid options are ignored)
Parsing documentation for mdless-1.0.3
Installing ri documentation for mdless-1.0.3
Installing darkfish documentation for mdless-1.0.3
Done installing documentation for mdless after 0 seconds
Parsing documentation for mdless-1.0.3
Done installing documentation for mdless after 0 seconds
Gems updated: mdless
```

And then trying to invoke `mdless` for anything (`mdless <filename>`, or `mdless --help` or even just `mdless`) gives the same error:

```ruby
mdless
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mdless/hash (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/mdless-1.0.3/lib/mdless.rb:9:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/mdless-1.0.3/bin/mdless:3:in `<top (required)>'
	from /usr/local/bin/mdless:22:in `load'
	from /usr/local/bin/mdless:22:in `<main>'
```

¯\\\_(ツ)\_/¯

**Comment by ttscoff** [comment]
Oh no. Will did today.

- Brett

**Comment by ttscoff** [comment]
Ok, had to bump a couple times because yanking 1.0.3 made a mess, but 
updating to 1.0.5 now should fix this issue.

**Comment by jjarava** [comment]
Works great now thanks!
