### ISSUE TITLE
macOS 10.15.3 - failing with "syntax error, unexpected $end, expecting ')'"

### ISSUE THREAD

**Issue by khorton** [ttscoff/mdless#47]
Fresh install on macOS 10.15.3.  Any attempt to run, including mdless -h fails with:

`%mdless -h

/opt/local/lib/ruby/gems/1.8/gems/mdless-1.0.10/lib/mdless/converter.rb:254: warning: don't put space before argument parentheses
/opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /opt/local/lib/ruby/gems/1.8/gems/mdless-1.0.10/lib/mdless/converter.rb:254: unknown type of %string (SyntaxError)
...h ('%3d: %s' % [idx + 1, c(%i[x black])+"."*level+c(%i[x yel...
                              ^
/opt/local/lib/ruby/gems/1.8/gems/mdless-1.0.10/lib/mdless/converter.rb:254: syntax error, unexpected $end, expecting ')'
...h ('%3d: %s' % [idx + 1, c(%i[x black])+"."*level+c(%i[x yel...
                              ^
	from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /opt/local/lib/ruby/gems/1.8/gems/mdless-1.0.10/lib/mdless.rb:11
	from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /opt/local/lib/ruby/gems/1.8/gems/mdless-1.0.10/bin/mdless:3
	from /opt/local/bin/mdless:19:in `load'
	from /opt/local/bin/mdless:19`

**Comment by ttscoff** [comment]
What Ruby version are you running? The default 2.6 that comes with macOS 
10.15?

-Brett

**Comment by khorton** [comment]
Thanks for the hint.  It turned out that I had a forgotten gem in my path that called ruby1.8.  I renamed that one to gem1.8, installed mdless again, and now it seems to work as expected.

Sorry for the noise.
